version: "3.8"

services:
  mysqldb:
    image: mysql:8.0.28
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
      - ./db:/tmp/test
    hostname: db_source
    networks:
      - new_be

  library-backend:
    depends_on:
      - mysqldb
    build: ./Backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
      - GMAIL= $GMAIL
      - GMAIL_PASS= $GMAIL_PASS
      - CLOUDINARY_NAME=$CLOUDINARY_NAME
      - CLOUDINARY_KEY=$CLOUDINARY_KEY
      - CLOUDINARY_SECRET=$CLOUDINARY_SECRET
    volumes:
      - ./configELK/filebeat.yml:/etc/filebeat/filebeat.yml
    user: root
    networks:
      - new_fe
      - new_be

  library-frontend:
    depends_on:
      - library-backend
    build:
      context: ./Frontend
      args:
        - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    networks:
      - new_fe

  datawarehouse:
    image: mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DW_ROOT_PASSWORD
      - MYSQL_DATABASE=$DW_DATABASE
    ports:
      - $DW_LOCAL_PORT:$DW_DOCKER_PORT
    volumes:
      - ./DataWarehouse/dwQuery.sql:/docker-entrypoint-initdb.d/dwQuery.sql
    hostname: db_destination
    networks:
      - new_be

  elk:
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./configELK/02-beats-input.conf:/etc/logstash/conf.d/02-beats-input.conf
      - ./configELK/kibana.yml:/opt/kibana/config/kibana.yml
      - ./configELK/logstash.yml:/opt/logstash/config/logstash.yml
      - ./configELK/pipelines.yml:/opt/logstash/config/pipelines.yml
      - ./configELK/elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml
    user: root
    hostname: elk
    networks:
      - new_be

  etl:
    depends_on:
      - mysqldb
      - library-backend
      - elk
    # restart: unless-stopped
    build:
      context: ./etl
    networks:
      - new_be

volumes:
  db:
networks:
  new_be:
  new_fe:
